### ISSUE TITLE
Please Update to Latest Version

### ISSUE THREAD

**Issue by osyduck** [anysz/ovopy#2]
Traceback (most recent call last):
  File "tes.py", line 13, in <module>
    lsc   = ovo.loginSecurityCode('252101', vl2fa.updateAccessToken)
  File "D:\PythonLib\ovo\ovo\ovopy\main.py", line 88, in loginSecurityCode
    return self.client.loginSecurityCode(pin_code,updateAccessToken)
  File "D:\PythonLib\ovo\ovo\ovopy\api\client.py", line 171, in loginSecurityCode
    raise OVOUnexpectedError(err)
error.OVOUnexpectedError: OVOHttpResponse(code=9999, status=None, message='Please update to the latest version of OVO app to enjoy all the features offered by OVO', content=None, data=None, httpStatus=410)

could you help me to update this script?

**Comment by osyduck** [comment]
Solved by changing app version header to 'app_version' : '3.8.1' in main.py line 14
